### ISSUE TITLE
Rascunhar primeiras ideias do Controle.se

### ISSUE THREAD

**Issue by Fernando-crz** [brunoastephan/MAC350---Controle.se#1]
Descrição:

Nossa objetivo é criar um aplicativo Android que tem como intuito ajudar o usuário no controle financeiro de gastos ao longo do tempo. Utilizaremos Kotlin para nossa aplicação.

Passos para reproduzir:

- [x] Criar um README para descrever o projeto de forma breve, inicialmente
- [x] Criar um aplicativo "vazio" para compreender interface de criação de aplicativos via Kotlin
- [x] Fazer primeiros _sketches_ demonstrando ideia de funcionamento inicial do aplicativo
- [x] Criar _Wireframe_ da interface do aplicativo
- [x] #2

**Comment by brunoastephan** [comment]
![1](https://github.com/brunoastephan/MAC350---Controle.se/assets/83648801/d0000b41-dca6-432b-80d4-7f46a657090d)
![2](https://github.com/brunoastephan/MAC350---Controle.se/assets/83648801/ae6f9cba-1dab-4c9e-94d4-e1606a9fdccb)
![3](https://github.com/brunoastephan/MAC350---Controle.se/assets/83648801/2937c269-bd76-4312-8d5e-ee0993d040da)

Primeiros sketches

**Comment by Fernando-crz** [comment]
![projeto-sketch_annotated-1](https://github.com/brunoastephan/MAC350---Controle.se/assets/86577259/d76b5613-61aa-46be-aac5-343fc2891476)

Sketches adicionais sobre segunda possibilidade de ideia de interface do aplicativo

**Comment by brunoastephan** [comment]
Protótipo Wireframe no Figma:

https://www.figma.com/file/w4KXgLn0k0QqGsaWpXhiGP/MAC0350---Controle.se?type=design&node-id=0%3A1&mode=dev&t=hc7D51oE86SZ5wWO-1

**Comment by brunoastephan** [comment]
> Protótipo Wireframe no Figma:
> 
> https://www.figma.com/file/w4KXgLn0k0QqGsaWpXhiGP/MAC0350---Controle.se?type=design&node-id=0%3A1&mode=dev&t=hc7D51oE86SZ5wWO-1

Agora está completo
